library(Seurat)

## read in the final annotated ge_So object
ge_so <- readRDS('/data1/APA/Paul_ALS_Data/ALS_snRNA_final.RDS')
ge_so <- subset(ge_so, subset=chemistry=='V3')
## filter the V3
ge_so <- SetIdent(ge_so, value = ge_so$Velm_cellsubtype)


exp_profiles <- AverageExpression(ge_so)
dim(exp_profiles[['SCT']])
write.table(exp_profiles[['SCT']], '/home/aiden/codes/APA_stuff/post_qual/APA/For_DL_model/celltype_profiles.tsv', sep='\t',
          quote=F)

table(ge_so$celltype)
table(ge_so$Velm_cellsubtype)

ge_so <- SetIdent(ge_so, value = ge_so$celltype)


exp_profiles = data.frame(exp_profiles[['SCT']])

exp_profiles2 <- AverageExpression(ge_so)
exp_profiles2 <- data.frame(exp_profiles2[['SCT']])
exp_profiles$Excitatory <- exp_profiles2$Excitatory
exp_profiles$Inhibitory <- exp_profiles2$Inhibitory


write.table(exp_profiles, '/home/aiden/codes/APA_stuff/post_qual/APA/For_DL_model/celltype_profiles.tsv', sep='\t',
            quote=F)
colnames(exp_profiles)
new_names = c('Oligodendrocytes', 'OPC','AST-PP', 'AST-FB', 'Microglia', 'Endothelial', 'L2-3', 'L4', 'L5-6',
              'L5-6-CC', "Neu-NRGN.II", 'IN-PV', 'IN-SST', 'IN-SV2C', 'IN-VIP', 'Excitatory', 'Inhibitory')
colnames(exp_profiles) <- new_names

write.table(exp_profiles, '/home/aiden/codes/APA_stuff/post_qual/APA/For_DL_model/celltype_profiles.tsv', sep='\t',
            quote=F)





ge_so@active.assay <- 'RNA'

ge_so <- NormalizeData(ge_so, normalization.method = "LogNormalize", scale.factor = 10000, verbose = FALSE)
ge_so <- FindVariableFeatures(ge_so, nfeatures = 2000)
VariableFeatures(ge_so)


## read in the all RBP names
RBPS = read.table('/home/aiden/codes/APA_stuff/post_qual/APA/For_DL_model/RBP_Information.txt', header=T, sep='\t')
RBP_names = RBPS$RBP_Name

length(which(RBP_names %in% rownames(ge_so) ))


features_to_keep = unique(c(RBP_names,VariableFeatures(ge_so)))

length(which(features_to_keep %in% rownames(exp_profiles2$SCT)))

exp_profiles_main_ct <- data.frame(exp_profiles2$SCT)
tst <- data.frame(exp_profiles$SCT, exp_profiles_main_ct$Excitatory, exp_profiles_main_ct$Inhibitory)
new_names = c('Oligodendrocytes', 'OPC','AST-PP', 'AST-FB', 'Microglia', 'Endothelial', 'L2-3', 'L4', 'L5-6',
             'L5-6-CC', "Neu-NRGN.II", 'IN-PV', 'IN-SST', 'IN-SV2C', 'IN-VIP', 'Excitatory', 'Inhibitory')
colnames(tst) = new_names                          
head(tst)

final_exp_profiles <- tst %>% filter(rownames(tst) %in% features_to_keep)
final_exp_profiles <- t(scale(t(final_exp_profiles)))
head(final_exp_profiles)

write.table(final_exp_profiles, '/home/aiden/codes/APA_stuff/post_qual/APA/For_DL_model/celltype_profiles.tsv', sep='\t',
            quote=F)

#summary: celltype profiles are generated by these steps:
#  1- features are SC transformed
#  2- got 2000 valiable features from RNA assay ( after normalization)
#  3- got list of ALL RBPS
#  4- we selected all the variable features and all expressed RBPS
#  5- scaled the featers (for deep learning!)

85 * 16 + 85 * 8 

14 * 85 + 85 * 8 
8 * 85
336 * 1.13 + 96 

14 * 60 + 10 *40 - 40 + 400 


## read in the final annotated ge_So object

library(Seurat)
library(SeuratData)
library(SeuratDisk)

ge_so <- readRDS('/data1/APA/Paul_ALS_Data/ALS_snRNA_final.RDS')
ge_so <- subset(ge_so, subset=chemistry=='V3')


DefaultAssay(ge_so) <- 'RNA'
ge_so@assays[['SCT']] <- NULL
ge_so@assays[['integrated']] <- NULL
SaveH5Seurat(ge_so, filename = "/data1/APA/Paul_ALS_Data/als.h5Seurat")
Convert("/data1/APA/Paul_ALS_Data/als.h5Seurat", dest = "h5ad")



######## lets do this with scVI
library(Seurat)
library(reticulate)
library(SeuratData)
library(devtools)
devtools::install_github("cellgeni/sceasy")
library(sceasy)

ge_so <- NormalizeData(ge_so, normalization.method = "LogNormalize", scale.factor = 10000)
ge_so <- FindVariableFeatures(ge_so, selection.method = "vst", nfeatures = 5000)

sc <- import("scanpy", convert = FALSE)
scvi <- import("scvi", convert = FALSE)
adata <- convertFormat(ge_so, from="seurat", to="anndata", main_layer="counts", drop_single_values=FALSE)
print(adata) #

# run setup_anndata
scvi$model$SCVI$setup_anndata(adata)

# create the model
model = scvi$model$SCVI(adata)

# train the model
model$train()

# get the latent represenation
latent = model$get_latent_representation()

# put it back in our original Seurat object
latent <- as.matrix(latent)
rownames(latent) = colnames(ge_so)
ge_so[["scvi"]] <- CreateDimReducObject(embeddings = latent, key = "scvi_", assay = DefaultAssay(ge_so))

ge_so <- FindNeighbors(ge_so, dims = 1:10, reduction = "scvi")
ge_so <- FindClusters(ge_so, resolution =1)

ge_so <- RunUMAP(ge_so, dims = 1:10, reduction = "scvi", n.components = 2)

ge_so <- SetIdent(ge_so, value = ge_so$Velm_cellsubtype)
DimPlot(ge_so, reduction = "umap", pt.size = 0.2)


ge_so <- SetIdent(ge_so, value = ge_so$diagnosis_Velm_cellsubtype)

tst = FindMarkers(
  ge_so,
  ident.1 = 'C9ALSFTLD_Oligodendrocytes',
  ident.2 = 'control_Oligodendrocytes',
  assay = NULL,
  slot = "data",
  reduction = 'scvi')

tdim(tst)

## ok it works I can get 10 dim profiles.... need to run c9ALS-celltype vs control

table(ge_so$diagnosis)
simplfy_diag <- function(x){
  out = 'C9noALS'
  if (grepl('control', x, fixed = TRUE)){
    out = 'CTRL'
  }
  if (grepl('C9ALS', x, fixed = TRUE)){
    out = 'C9ALS'
  }
  if (grepl('sALS', x, fixed = TRUE)){
    out = 'sALS'
  }
  return(out)
}

tst = data.frame(ge_so$diagnosis)
ge_so$simple_diagnosis <- apply(tst,MARGIN=1,FUN=simplfy_diag )
table(ge_so$simple_diagnosis)

ge_so$diagnosis_celltype <- paste0(ge_so$simple_diagnosis,'_', ge_so$celltype)

table(ge_so$diagnosis_celltype)
ge_so <- SetIdent(ge_so, value = ge_so$diagnosis_celltype)
# make C9ALS profiles:
profiles <- list()
for (ct in unique(ge_so$celltype)){
  diff <- FindMarkers(
    ge_so,
    ident.1 = paste0('C9ALS_', ct),
    ident.2 = paste0('CTRL_', ct),
    assay = NULL,
    slot = "data",
    reduction = 'scvi')
  profiles[[ct]] <- diff$avg_diff
}

##

c9als_profiles <- data.frame(profiles)



profiles <- list()
for (ct in unique(ge_so$celltype)){
  diff <- FindMarkers(
    ge_so,
    ident.1 = paste0('sALS_', ct),
    ident.2 = paste0('CTRL_', ct),
    assay = NULL,
    slot = "data",
    reduction = 'scvi')
  profiles[[ct]] <- diff$avg_diff
}

sAls_profiles <- data.frame(profiles)


write.table(c9als_profiles, '/data1/APA/Paul_ALS_Data/bams_in/subscelltype_bamfiles/Mapper_outs/data_for_DL/C9ALS_CTRL_profiles.tsv', sep='\t',
           quote=F)


write.table(sAls_profiles, '/data1/APA/Paul_ALS_Data/bams_in/subscelltype_bamfiles/Mapper_outs/data_for_DL/sALS_CTRL_profiles.tsv', sep='\t',
            quote=F)

## lets save the 
sub_cells <- c()

for (ct in unique(ge_so$diagnosis_Velm_cellsubtype)){
  if (grepl( 'control', ct, fixed = TRUE)){
    sub_cells <- c(sub_cells, ct)
  }
}

main_cells <- c()

for (ct in unique(ge_so$diagnosis_celltype)){
  if (grepl( 'CTRL', ct, fixed = TRUE)){
    main_cells <- c(main_cells, ct)
  }
}



all_avg_embeddings = list()
for (sub_ct in sub_cells){
  idx = which(ge_so$diagnosis_Velm_cellsubtype == sub_ct)
  all_avg_embeddings[[sub_ct]] <- colMeans(Embeddings(object = ge_so[["scvi"]])[idx,])
}

for (sub_ct in main_cells){
  idx = which(ge_so$diagnosis_celltype == sub_ct)
  all_avg_embeddings[[sub_ct]] <- colMeans(Embeddings(object = ge_so[["scvi"]])[idx,])
}

ctrl_profile <- data.frame(all_avg_embeddings)
colnames(ctrl_profile) <- c("L5_6_CC","Oligodendrocytes","AST_PP","IN_SST", "Microglia", "OPC","L2_3","IN_VIP",
                            "IN_PV", "L4","AST_FB", "IN_SV2C" ,"L5_6","Endothelial","Excitatory", "Oligodendrocytes",
                            "Astrocytes","Inhibitory","Microglia","OPC","Endothelial")

write.table(ctrl_profile, '/data1/APA/Paul_ALS_Data/bams_in/subscelltype_bamfiles/Mapper_outs/data_for_DL/all_ctrl_embeddings.csv',
            sep=',',quote=F)

## lets save
saveRDS(ge_so, '/data1/APA/Paul_ALS_Data/ALS_snRNA_final_with_scVI.RDS')

### digress part
####  getting the Astrocytes bam files 
ct <- 'Astrocytes'
so <- subset(ge_so, subset=celltype == 'Astrocytes')
so$cellnames <- Cells(so)
cell_sample_df <- data.frame(cells= so$cellnames, sample=so$sample)
for (sample in unique(so$sample)){
  tmp_df <- cell_sample_df[cell_sample_df$sample == sample,]
  tmp_df <- tmp_df %>% mutate(bc= sub(".*_(.*)","\\1",cells))
  outname <- paste0('/data1/APA/Paul_ALS_Data/bams_in/subscelltype_bamfiles/',ct,'/',sample,'_barcodes.tsv')
  write.table(tmp_df$bc, file=outname, quote=F, row.names=F, col.names=F)
}
filename <- paste0("/data1/APA/Paul_ALS_Data/bams_in/subscelltype_bamfiles/",ct,"/subset_bamfiles.sh")
outfile <- file(filename)
outlines = c()
for (sample in unique(so$sample)){
  bc = paste0(sample,'_barcodes.tsv')
  bamfiles = paste0(' /data1/APA/Paul_ALS_Data/bams_in/',sample,'_filtered.bam')
  outname = paste0(" ",sample,'_CTfiltered.bam')
  subset_arg = '~/softwares/subset_bam --bam '
  bc_arg = ' --cell-barcodes '
  out_arg = ' --out-bam'
  outline = paste0(subset_arg,bamfiles, bc_arg, bc, out_arg,outname, " &")
  outlines <- append(outlines, outline)
}
writeLines(outlines, outfile)
close(outfile)

#########

# lets get the 10d vector per diagnasis_Velm_ct and diagnasosi_main_CT

table(ge_so$celltype)

